name: CD
on:
  - push
  - pull_request

jobs:
  
      
  svg:
    name: Mac OS X qtsvg
    runs-on: macos-11
    if: False

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        wget https://github.com/sunderme/homebrew-qt6/releases/download/6.4.0-1/QtBase-6.4.0-Darwin.tar.xz
        sudo tar xvf ./QtBase-6.4.0-Darwin.tar.xz -C /usr/local
        rm QtBase-6.4.0-Darwin.tar.xz

    - name: Build dependency
      run: |
        brew install ninja

    - name: Download source
      run: |
        wget https://download.qt.io/official_releases/qt/6.4/6.4.0/submodules/qtsvg-everywhere-src-6.4.0.tar.xz
        tar xvf qtsvg-everywhere-src-6.4.0.tar.xz
        rm qtsvg-everywhere-src-6.4.0.tar.xz

    - name: Build
      run: |
        cd qtsvg-everywhere-src-6.4.0
        echo "include(CPack)">>CMakeLists.txt
        mkdir build
        cd build
        echo
        /usr/local/QtBase-6.4.0-Darwin/bin/qt-cmake .. -G Ninja
        cmake --build . --parallel
        
    - name: Package
      id: package
      run: |
        cd qtsvg-everywhere-src-6.4.0
        cd build
        cpack -G TXZ
        cp *.xz ../..
        pwd

    - name: Archive bottle
      uses: actions/upload-artifact@v3
      with:
        name: qt6-svg
        path: Qt*.tar.xz

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Qt*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

  qt5compat:
    name: Mac OS X qt5compat
    runs-on: macos-11
    if: False

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        wget https://github.com/sunderme/homebrew-qt6/releases/download/6.4.0-1/QtBase-6.4.0-Darwin.tar.xz
        sudo tar xvf ./QtBase-6.4.0-Darwin.tar.xz -C /usr/local
        rm QtBase-6.4.0-Darwin.tar.xz

    - name: Build dependency
      run: |
        brew install ninja

    - name: Download source
      run: |
        wget https://download.qt.io/official_releases/qt/6.4/6.4.0/submodules/qt5compat-everywhere-src-6.4.0.tar.xz
        tar xvf qt5compat-everywhere-src-6.4.0.tar.xz
        rm qt5compat-everywhere-src-6.4.0.tar.xz

    - name: Build
      run: |
        cd qt5compat-everywhere-src-6.4.0
        echo "include(CPack)">>CMakeLists.txt
        mkdir build
        cd build
        echo
        /usr/local/QtBase-6.4.0-Darwin/bin/qt-cmake .. -G Ninja
        cmake --build . --parallel
        
    - name: Package
      id: package
      run: |
        cd qt5compat-everywhere-src-6.4.0
        cd build
        cpack -G TXZ
        cp *.xz ../..
        pwd

    - name: Archive bottle
      uses: actions/upload-artifact@v3
      with:
        name: qt6-qt5compat
        path: Qt*.tar.xz 

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Qt*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
    
  tools:
    name: Mac OS X tools
    runs-on: macos-11
    if: False

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        wget https://github.com/sunderme/homebrew-qt6/releases/download/6.4.0-1/QtBase-6.4.0-Darwin.tar.xz
        sudo tar xvf ./QtBase-6.4.0-Darwin.tar.xz -C /usr/local
        rm QtBase-6.4.0-Darwin.tar.xz

    - name: Build dependency
      run: |
        brew install ninja

    - name: Download source
      run: |
        wget https://download.qt.io/official_releases/qt/6.4/6.4.0/submodules/qttools-everywhere-src-6.4.0.tar.xz
        tar xvf qttools-everywhere-src-6.4.0.tar.xz
        rm qttools-everywhere-src-6.4.0.tar.xz

    - name: Build
      run: |
        cd qttools-everywhere-src-6.4.0
        echo "include(CPack)">>CMakeLists.txt
        mkdir build
        cd build
        echo
        /usr/local/QtBase-6.4.0-Darwin/bin/qt-cmake .. -G Ninja
        cmake --build . --parallel
        
    - name: Package
      id: package
      run: |
        cd qttools-everywhere-src-6.4.0
        cd build
        cpack -G TXZ
        cp *.xz ../..
        pwd

    - name: Archive bottle
      uses: actions/upload-artifact@v3
      with:
        name: qt6-tools
        path: Qt*.tar.xz 

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Qt*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

  charts:
    name: Mac OS X charts
    runs-on: macos-11
    if: False

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        wget https://github.com/sunderme/homebrew-qt6/releases/download/6.4.0-1/QtBase-6.4.0-Darwin.tar.xz
        sudo tar xvf ./QtBase-6.4.0-Darwin.tar.xz -C /usr/local
        rm QtBase-6.4.0-Darwin.tar.xz

    - name: Build dependency
      run: |
        brew install ninja

    - name: Download source
      run: |
        wget https://download.qt.io/official_releases/qt/6.4/6.4.0/submodules/qtcharts-everywhere-src-6.4.0.tar.xz
        tar xvf qtcharts-everywhere-src-6.4.0.tar.xz
        rm qtcharts-everywhere-src-6.4.0.tar.xz

    - name: Build
      run: |
        cd qtcharts-everywhere-src-6.4.0
        echo "include(CPack)">>CMakeLists.txt
        mkdir build
        cd build
        echo
        /usr/local/QtBase-6.4.0-Darwin/bin/qt-cmake .. -G Ninja
        cmake --build . --parallel
        
    - name: Package
      id: package
      run: |
        cd qtcharts-everywhere-src-6.4.0
        cd build
        cpack -G TXZ
        cp *.xz ../..
        pwd

    - name: Archive bottle
      uses: actions/upload-artifact@v3
      with:
        name: qt6-charts
        path: Qt*.tar.xz 

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Qt*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

  declarative:
    name: Mac OS X declarative
    runs-on: macos-11
    if: False

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        wget https://github.com/sunderme/homebrew-qt6/releases/download/6.4.0-1/QtBase-6.4.0-Darwin.tar.xz
        sudo tar xvf ./QtBase-6.4.0-Darwin.tar.xz -C /usr/local
        rm QtBase-6.4.0-Darwin.tar.xz

    - name: Build dependency
      run: |
        brew install ninja

    - name: Download source
      run: |
        wget https://download.qt.io/official_releases/qt/6.4/6.4.0/submodules/qtdeclarative-everywhere-src-6.4.0.tar.xz
        tar xvf qtdeclarative-everywhere-src-6.4.0.tar.xz
        rm qtdeclarative-everywhere-src-6.4.0.tar.xz

    - name: Build
      run: |
        cd qtdeclarative-everywhere-src-6.4.0
        echo "include(CPack)">>CMakeLists.txt
        mkdir build
        cd build
        echo
        /usr/local/QtBase-6.4.0-Darwin/bin/qt-cmake .. -G Ninja
        cmake --build . --parallel
        
    - name: Package
      id: package
      run: |
        cd qtdeclarative-everywhere-src-6.4.0
        cd build
        cpack -G TXZ
        cp *.xz ../..
        pwd

    - name: Archive bottle
      uses: actions/upload-artifact@v3
      with:
        name: qt6-declarative
        path: Qt*.tar.xz 

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Qt*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  
  quazip:
    name: Mac OS X quazip
    runs-on: macos-11
    if: True

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        wget https://github.com/sunderme/homebrew-qt6/releases/download/6.4.0-1/QtBase-6.4.0-Darwin.tar.xz
        sudo tar xvf ./QtBase-6.4.0-Darwin.tar.xz -C /usr/local
        rm QtBase-6.4.0-Darwin.tar.xz

    - name: Download source
      run: |
        wget https://github.com/stachenov/quazip/archive/v1.3.tar.gz
        tar xvf v1.3.tar.gz
        rm v1.3.tar.gz

    - name: Build
      run: |
        cd quazip-1.3
        echo "include(CPack)">>CMakeLists.txt
        mkdir build
        cd build
        echo
        /usr/local/QtBase-6.4.0-Darwin/bin/qt-cmake .. 
        cmake --build . --parallel
        
    - name: Package
      id: package
      run: |
        cd quazip-1.3
        cd build
        cpack -G TXZ
        cp *.xz ../..
        pwd

    - name: Archive bottle
      uses: actions/upload-artifact@v3
      with:
        name: quazip-qt6
        path: QUaZip*.tar.xz 

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: QuaZip*.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}


        
 
